# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filesearch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'filesearch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ilesearch.proto\x12\nfilesearch\"k\n\rSearchRequest\x12\x1a\n\rbase_path_key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0c\x66ile_pattern\x18\x02 \x01(\t\x12\x16\n\x0einclude_hidden\x18\x03 \x01(\x08\x42\x10\n\x0e_base_path_key\"<\n\x0eSearchResponse\x12\x13\n\x0b\x66ound_files\x18\x01 \x03(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t2V\n\x0c\x46ileSearcher\x12\x46\n\x0bSearchFiles\x12\x19.filesearch.SearchRequest\x1a\x1a.filesearch.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filesearch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=32
  _globals['_SEARCHREQUEST']._serialized_end=139
  _globals['_SEARCHRESPONSE']._serialized_start=141
  _globals['_SEARCHRESPONSE']._serialized_end=201
  _globals['_FILESEARCHER']._serialized_start=203
  _globals['_FILESEARCHER']._serialized_end=289
# @@protoc_insertion_point(module_scope)
